language: go
go:
  - 1.7
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - go test -v -cover -race -coverprofile=coverage.out
after_script:
  - go get github.com/mattn/goveralls
  - $HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=coverage.out -repotoken=$COVERALLS_TOKEN
